#!/bin/bash

cd ../examples
mkdir $4
cd $4
../../src/table_rnaseq_filter.exe ../rnaseq/$1 1 $2 $3 ../../genomes/protcod_dm6_m1kb_p100_tss.bed 5 up_$4 do_$4 no_$4
../../src/select_lines01.exe	../../genomes/m1kb_p100_dm6_err238tbp.tab	up_$4	up_$4.tab
../../src/select_lines01.exe	../../genomes/m1kb_p100_dm6_err238tbp.tab	do_$4	do_$4.tab
../../src/select_lines01.exe	../../genomes/m1kb_p100_dm6_err238tbp.tab	no_$4	no_$4.tab

for (( i=1; i <= $5; i++ )) {

../../src/minimax.exe	up_$4.tab no_$4.tab ../rnaseq/name_jaspar_insect_tf238_tbp ../rnaseq/name_jaspar_insects_class238_tbp $i 3.3 prc_up_$4 ext_up_$4 int_up_$4	out_up_$4 log_up_$4
../../src/minimax.exe	do_$4.tab no_$4.tab ../rnaseq/name_jaspar_insect_tf238_tbp ../rnaseq/name_jaspar_insects_class238_tbp $i 3.3 prc_do_$4 ext_do_$4 int_do_$4	out_do_$4 log_do_$4

}

cd ..
cd ..
