#!/bin/bash

ftype=("dbd" "mot" "per" "prb")
dire=("up" "do" "no")
tab="tab"
zo=("0" "1")

cd ../examples
mkdir $4
cd $4

../../src/table_rnaseq_adapted.exe ../rnaseq/$1 1 $2 $3 ../../genomes/protcod_dm6_m1kb_p100_tss.bed 5 200 1000 0.05 up_$4 do_$4 no_$4 0

for (( k=0; k<3; k++));
do
../../src/select_lines01.exe ../../genomes/protcod_dm6_m1kb_p100_tss_272tbp.tab ${dire[$k]}_$4 ${dire[$k]}_$4.tab
done

for (( k=0; k<2; k++));
do
for (( i=1; i<=$5; i+=$6 ));
do
../../src/minimax.exe	${dire[$k]}_$4.tab no_$4.tab ../rnaseq/jaspar2026_tfclass_insects272tbp $i $5 1 4 prc_${dire[$k]}_$4_$i prb_${dire[$k]}_$4_$i cex_${dire[$k]}_$4_$i cin_${dire[$k]}_$4_$i out_${dire[$k]}_$4_$i per_${dire[$k]}_$4_$i dbd_${dire[$k]}_$4_$i mot_${dire[$k]}_$4_$i log_${dire[$k]}_$4_$i
done
done


for (( j=0; j<4; j++));
do
for (( k=0; k<2; k++));
do
cp ${ftype[$j]}_${dire[$k]}_$4_1 ${ftype[$j]}_${dire[$k]}_$4
done
done
for (( j=0; j<4; j++));
do
for (( k=0; k<2; k++));
do
for (( i=1+$6; i<=$5; i+=$6 ));
do
cat ${ftype[$j]}$_{dire[$k]}_$4_$i >> ${ftype[$j]}$_{dire[$k]}_$4
done
done
done

for (( k=0; k<2; k++));
do
../../src/minimax_pars.exe	prb_{dire[$k]}_$4	dbd_{dire[$k]}_$4	mot_{dire[$k]}_$4	../rnaseq/jaspar2026_tfclass_insects272tbp	$5	1	$6	${zo[$k]}	dynamics	fold_{dire[$k]}_$4	fold_best	rank_dbd_{dire[$k]}_$4	rank_dbd_best	rank_mot_{dire[$k]}_$4	rank_mot_best	ratio_dbd_{dire[$k]}_$4	ratio_dbd_best	ratio_mot_{dire[$k]}_$4	ratio_mot_best
done

for (( j=0; j<4; j++));
do
table=${tab}_${ftype[$j]}
rm $table
for (( k=0; k<2; k++));
do
filen=${ftype[$j]}$_{dire[$k]}_$4
cat $filen >> $table 
done
done

cd ..
cd ..
