#!/bin/bash

cd ../examples
mkdir $4
cd $4

../../src/table_rnaseq_filter.exe ../rnaseq/$1 1 $2 $3 ../../genomes/protcod_dm6_m1kb_p100_tss.bed 5 2 1.25 0.05 up_$4 do_$4 no_$4
../../src/select_lines01.exe ../../genomes/m1kb_p100_dm6_err238tbp.tab up_$4 up_$4.tab
../../src/select_lines01.exe ../../genomes/m1kb_p100_dm6_err238tbp.tab do_$4 do_$4.tab
../../src/select_lines01.exe ../../genomes/m1kb_p100_dm6_err238tbp.tab no_$4 no_$4.tab

for (( i=1; i <= $5; i+= $6 )) {

../../src/minimax.exe	up_$4.tab no_$4.tab ../rnaseq/jaspar_tfclass_insects238tbp $i $5 4 prc_up_$4 prb_up_$4 cex_up_$4 cin_up_$4 out_up_$4 per_up_$4 dbd_up_$4 log_up_$4
../../src/minimax.exe	do_$4.tab no_$4.tab ../rnaseq/jaspar_tfclass_insects238tbp $i $5 4 prc_do_$4 prb_do_$4 cex_do_$4 cin_do_$4 out_do_$4 per_do_$4 dbd_do_$4 log_do_$4

}

cp dbd_up_$4_1 dbd_up_$4
cp dbd_do_$4_1 dbd_do_$4

cp prb_up_$4_1 prb_up_$4
cp prb_do_$4_1 prb_do_$4

cp per_up_$4_1 per_up_$4
cp per_do_$4_1 per_do_$4

for (( i=1 + $6; i <= $5; i+= $6 )) {

cat dbd_up_$4_$i >> dbd_up_$4
cat dbd_do_$4_$i >> dbd_do_$4

cat prb_up_$4_$i >> prb_up_$4
cat prb_do_$4_$i >> prb_do_$4

cat per_up_$4_$i >> per_up_$4
cat per_do_$4_$i >> per_do_$4

}

../../src/minimax_pars.exe	prb_up_$4	dbd_up_$4	$5	1	$6	1	rank_evo_up_$4	fold_evo_up_$4	rank_best	fold_best	dynamics
../../src/minimax_pars.exe	prb_do_$4	dbd_do_$4	$5	1	$6	1	rank_evo_do_$4	fold_evo_do_$4	rank_best	fold_best	dynamics


cd ..
cd ..
