#!/bin/bash

ftype=("dbd" "mot" "per" "prb")
dire=("_up_" "_do_")
tab="tab"
emp="_"

cd ../examples
mkdir $4
cd $4

../../src/table_rnaseq_adapted.exe ../rnaseq/$1 1 $2 $3 ../../genomes/protcod_dm6_m1kb_p100_tss.bed 5 200 1000 0.05 up_$4 do_$4 no_$4 0
../../src/select_lines01.exe ../../genomes/protcod_dm6_m1kb_p100_tss_272tbp.tab up_$4 up_$4.tab
../../src/select_lines01.exe ../../genomes/protcod_dm6_m1kb_p100_tss_272tbp.tab do_$4 do_$4.tab
../../src/select_lines01.exe ../../genomes/protcod_dm6_m1kb_p100_tss_272tbp.tab no_$4 no_$4.tab

for (( i=1; i <= $5; i+= $6 )) {

../../src/minimax.exe	up_$4.tab no_$4.tab ../rnaseq/jaspar2026_tfclass_insects272tbp $i $5 1 4 prc_up_$4 prb_up_$4 cex_up_$4 cin_up_$4 out_up_$4 per_up_$4 dbd_up_$4 mot_up_$4 log_up_$4
../../src/minimax.exe	do_$4.tab no_$4.tab ../rnaseq/jaspar2026_tfclass_insects272tbp $i $5 1 4 prc_do_$4 prb_do_$4 cex_do_$4 cin_do_$4 out_do_$4 per_do_$4 dbd_do_$4 mot_do_$4 log_do_$4

}

for (( i=0; i<4; i++));
do
for (( k=0; k<2; k++));
do
cp ${ftype[$i]}${dire[$k]}$4${emp}1 ${ftype[$i]}${dire[$k]}$4
done
done

for (( i=1 + $6; i <= $5; i+= $6 ));
do
for (( k=0; k<2; k++));
do
cat ${ftype[$i]}${dire[$k]}$4{emp}$i >> ${ftype[$i]}${dire[$k]}$4
done
done

../../src/minimax_pars.exe	prb_up_$4	dbd_up_$4	mot_up_$4 ../rnaseq/jaspar_tfclass_insects272tbp $5	1	$6	1	rank_dbd_up_$4 rank_mot_up_$4 fold_up_$4	rank_dbd_best_$4 rank_mot_best_$4 fold_best_$4	dynamics_$4
../../src/minimax_pars.exe	prb_do_$4	dbd_do_$4	mot_do_$4 ../rnaseq/jaspar_tfclass_insects272tbp $5	1	$6	0	rank_dbd_do_$4 rank_mot_do_$4 fold_do_$4	rank_dbd_best_$4 rank_mot_best_$4 fold_best_$4	dynamics_$4

for (( i=0; i<4; i++));
do
table=${tab}${emp}${ftype[$i]}
rm $table
for (( k=0; k<2; k++));
do
filen=${ftype[$i]}${dire[$k]}$4
cat $filen >> $table 
done
done

cd ..
cd ..
