#!/bin/sh

./gmsga_rnaseq E-MTAB-9805-query-results.tsv 3 4 orco1 50 1
./gmsga_rnaseq E-MTAB-9805-query-results.tsv 5 6 orco4 50 1
./gmsga_rnaseq E-MTAB-9805-query-results.tsv 7 8 peb1 50 1
./gmsga_rnaseq E-MTAB-9805-query-results.tsv 9 10 peb4 50 1
